snippets:
# cd
  - name: ..
    keyword: ..
    snippet: cd ..

  - name: ...
    keyword: ...
    snippet: cd ../..

# ls
  - name: ls
    keyword: ls
    snippet: gls --color=auto

  - name: la
    keyword: la
    snippet: gls --color=auto -la

  - name: ll
    keyword: ll
    snippet: gls --color=auto -l

# git
  - name: g
    keyword: g
    snippet: git

  - name: gs
    keyword: gs
    snippet: git status --short --branch

  - name: gf
    keyword: gf
    snippet: git fetch

  - name: gb
    keyword: gb
    snippet: git branch

  - name: ga
    keyword: ga
    snippet: git add

  - name: gcm
    keyword: gcm
    snippet: git commit -m '{{commit_message}}'

  - name: gcnm
    keyword: gcnm
    snippet: git commit --no-verify -m '{{commit_message}}'

  - name: gw
    keyword: gw
    snippet: git switch

  - name: gwc
    keyword: gwc
    snippet: git switch -c

  - name: gw-
    keyword: gw-
    snippet: git switch -

  - name: gp
    keyword: gp
    snippet: git pull

  - name: gpst
    keyword: gpst
    snippet: git push origin --tags

  - name: grb
    keyword: grb
    snippet: git rebase

  - name: grbc
    keyword: grbc
    snippet: git rebase --continue

  - name: grba
    keyword: grba
    snippet: git rebase --abort

# npm, yarn
  - name: ns
    keyword: ns
    snippet: npm run start

  - name: ys
    keyword: ys
    snippet: yarn start

  - name: yt
    keyword: yt
    snippet: yarn test

  - name: yb
    keyword: yb
    snippet: yarn build

# docker
  - name: d
    keyword: d
    snippet: docker

  - name: dp
    keyword: dp
    snippet: docker ps

  - name: dpa
    keyword: dpa
    snippet: docker ps -a

  - name: dcud
    keyword: dcud
    snippet: docker-compose up -d

  - name: dcst
    keyword: dcst
    snippet: docker-compose start

  - name: dcsp
    keyword: dcsp
    snippet: docker-compose stop

# shell
  - name: szp
    keyword: szp
    snippet: source ~/.zsh/.zprofile

  - name: szr
    keyword: szr
    snippet: source ~/.zsh/.zshrc

  - name: es
    keyword: es
    snippet: exec $SHELL -l

# others
  - name: v
    keyword: v
    snippet: vim

  - name: t
    keyword: t
    snippet: tig

  - name: path
    keyword: path
    snippet: echo $PATH | tr ':' '\n'
