#!/usr/bin/env zsh

ARGS="$@"

# these are commands I commonly call on commit hashes.
# cp->cherry-pick, co->checkout

if [[ $ARGS == 'git cp'* || \
        $ARGS == 'git cherry-pick'* || \
        $ARGS == 'git co'* || \
        $ARGS == 'git checkout'* || \
        $ARGS == 'git reset'* || \
        $ARGS == 'git show'* || \
        $ARGS == 'git log'* ]]; then
    _fzf_complete "--reverse --multi" "$@" < <(__git_log)
else
    eval "zle ${fzf_default_completion:-expand-or-complete}"
fi