#! /usr/bin/env zsh
# shellcheck shell=sh

local command=$1
shift

case "${command}" in


cd) fzf --preview 'tre --color=always --editor {}' "$@" ;;
export | unset) fzf --preview "eval 'echo \$'{}" "$@" ;;
ssh) fzf --preview 'dig {}' "$@" ;;
*) fzf --preview 'bat -n --color=always {}' "$@" ;;
esac

unset command
4
