#!/bin/bash

# Brew
# -----------------------------------------------------------------------------
brew update
brew upgrade
brew cleanup -s
brew cask cleanup
#now diagnotic
brew doctor
brew missing
apm upgrade -c false
/opt/bin/updateCCTF.sh && \
    terminal-notifier -message “git pull done” -title “CCTF up to date”
