#!/usr/bin/env zsh

# Select file from git status
gfi() {
  git rev-parse HEAD > /dev/null 2>&1 || return
  git -c color.status=always status --short |
  fzf --height 40% --reverse -m --ansi --nth 2..,.. \
    --preview '(git diff --color=always -- {-1} | sed 1,4d; cat {-1}) | head -500' |
  cut -c4- | sed 's/.* -> //'
}
