#! /usr/bin/env zsh

# prep the compinit function for use 
autoload -Uz compinit

_comp_path="${XDG_CACHE_HOME:-$HOME/.cache}/ zcompdump"

if [[ $_comp_path(#qNmh-20) ]]; then
  compinit -C -d "$_comp_path"
else
  mkdir -p "$_comp_path:h"
  compinit -i -d "$_comp_path"
  touch "$_comp_path"
fi

unset _comp_path

# run the compinit function to initialize completions 
compinit

# preps the complist module for enhanced completion listing
autoload -Uz complist

zinit cdreplay -q
