#! /usr/bin/env zsh

# -- dotfiles env-vars --
export DOTFILES="$HOME/.dotfiles"
export DOT_HOOKS_HOME="$DOTFILES/hooks"
export DOT_CONFIGS_HOME="$DOTFILES/config"
export DOT_FUNCTIONS_HOME="$DOTFILES/functions"

# -- zsh env-vars --
export ZDOTDIR="$DOT_CONFIG_HOME/zsh"

# setup zinit env-vars
typeset -gA ZINIT
typeset -gx ZINIT_HOME="${XDG_DATA_HOME}/zinit/zinit.git"
typeset -gx ZINIT_PLUGINS_DIR="$ZINIT_HOME/plugins"
typeset -gx ZINIT_SNIPPETS_DIR="$ZINIT_HOME/snippets"
typeset -gx ZINIT_COMPLETIONS_DIR="$ZINIT_HOME/completions"
typeset -gx ZINIT_BIN_DIR_NAME="$ZINIT_HOME/bin"
typeset -gx ZPFX="$ZINIT_HOME/polaris"

ZINIT[HOME_DIR]="$HOME/.local/share/zinit"
ZINIT[BIN_DIR]="$ZINIT_HOME/bin"
ZINIT[PLUGINS_DIR]="${ZINIT[HOME_DIR]}/plugins"
ZINIT[COMPLETIONS_DIR]="${ZINIT[HOME_DIR]}/completions"
ZINIT[SNIPPETS_DIR]="${ZINIT[HOME_DIR]}/snippets"
ZINIT[ZCOMPDUMP_PATH]="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump-$ZSH_VERSION"
ZINIT[LIST_COMMAND]=ls

ZINIT[INSTALL_URL]="https://github.com/zdharma-continuum/zinit.git"
ZINIT[OPTIMIZE_OUT_DISK_ACCESSES]=1
ZINIT[COMPINIT_OPTS]=" -C"
ZINIT[NO_ALIASES]=1

export LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
