#! /usr/bin/env zsh

# Set up Zinit environment variables
typeset -gx ZINIT_HOME="$HOME/.local/share/zinit"
typeset -gx ZPFX="$ZINIT_HOME/polaris"
typeset -gx ZINIT_BIN_DIR_NAME="$ZINIT_HOME"
typeset -gx ZINIT_PLUGINS_DIR="$ZINIT_HOME/plugins"
typeset -gx ZINIT_COMPLETIONS_DIR="$ZINIT_HOME/completions"
typeset -gx ZINIT_SNIPPETS_DIR="$ZINIT_HOME/snippets"

# Set up Zinit environment variables
typeset -gA ZINIT
ZINIT[HOME_DIR]="$ZINIT_HOME"
ZINIT[BIN_DIR]="$ZINIT_HOME"
ZINIT[PLUGINS_DIR]="${ZINIT[HOME_DIR]}/plugins"
ZINIT[COMPLETIONS_DIR]="${ZINIT[HOME_DIR]}/completions"
ZINIT[SNIPPETS_DIR]="${ZINIT[HOME_DIR]}/snippets"
ZINIT[ZCOMPDUMP_PATH]="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump-$ZSH_VERSION"
ZINIT[COMPINIT_OPTS]=" -C"
ZINIT[OPTIMIZE_OUT_DISK_ACCESSES]=1
ZINIT[NO_ALIASES]=1
ZINIT[LIST_COMMAND]="lsd"
ZINIT[INSTALL_URL]="https://github.com/zdharma-continuum/zinit.git"

# Install Zinit if not already installed
[[ ! -f $ZINIT_HOME/bin/zinit.zsh ]] &&
  command mkdir -p "$ZINIT_HOME/bin" &&
  command chmod g-rwX "$ZINIT_HOME/bin" &&
  command git clone "${ZINIT[INSTALL_URL]}" "$ZINIT_HOME/bin"

# Source Zinit
[[ -f "$ZINIT_HOME/bin/zinit.zsh" ]] && . "$ZINIT_HOME/bin/zinit.zsh"

# enhances zinits abilites via ice-enhancing annexes
zinit for \
  id-as'gem-node' @zdharma-continuum/zinit-annex-bin-gem-node \
  id-as'bin-symlink' @zdharma-continuum/zinit-annex-binary-symlink \
  id-as'default-ice' @zdharma-continuum/zinit-annex-default-ice \
  id-as'patch-dl' @zdharma-continuum/zinit-annex-patch-dl \
  id-as'rust' @zdharma-continuum/zinit-annex-rust
