#! /usr/bin/env zsh

export HOMEBREW_NO_ANALYTICS=1

# File where the list of path is cached.
PATH_CACHE="${HOME}/.path-env-cache"

# Force a cache refresh if file doesn't exist or older than 7 days.
# Source: https://gist.github.com/ctechols/ca1035271ad134841284#gistcomment-3109177
() {
    setopt extendedglob local_options
    if [[ ! -e ${PATH_CACHE} || -n ${PATH_CACHE}(#qN.md+7) ]]; then
        # Ordered list of path.
        PATH_LIST=(
            /usr/local/sbin
            $(brew --prefix eza)/bin
            $(brew --prefix uutils-coreutils)/libexec/uubin
            $(brew --prefix grep)/libexec/gnubin
            $(brew --prefix uutils-findutils)/libexec/uubin
            $(brew --prefix findutils)/bin
            $(brew --prefix gnu-sed)/libexec/gnubin
            $(brew --prefix gnu-tar)/libexec/gnubin
            $(brew --prefix openssh)/bin
            $(brew --prefix curl)/bin
            $(brew --prefix python@3.12)/libexec/bin
            ${HOME}/.cargo/bin
            # Required by pipx.
            ${HOME}/.local/bin
            /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
        )
        print -rl -- ${PATH_LIST} > ${PATH_CACHE}
    fi
}

# Cache exists and has been refreshed in the last 24 hours: load it.
# Source: https://stackoverflow.com/a/41212803
for line in "${(@f)"$(<${PATH_CACHE})"}"
{
    # Prepend paths. Source: https://stackoverflow.com/a/9352979
    path[1,0]=${line}
}


