#!/usr/local/bin/zsh
# Print pretty JSON
if [ $# -gt 0 ]
then
  for arg in $@
  do
    if [ -f $arg ]
    then
      less $arg | python -m json.tool
    else
      echo "$arg" | python -m json.tool
    fi
  done
fi
