#! /usr/bin/env zsh

# Usage: set_xdg <config|data|cache> <ENV_VAR> <CONFIG_FILE>

emulate -L zsh

local type=$1 var=$2 path=$3

case ${(L)type} in
    xdgconfig|config)
        type="CONFIG"
        ;;
    xdgdata|data)
        type="DATA"
        ;;
    xdgcache|cache)
        type="CACHE"
        ;;
    *)
        echo "Unknown XDG type: $1" >&2
        return 1
        ;;
esac
