#!/usr/bin/env zsh

# Extract the flag from the first argument and remove the leading '--'
flag="${1#--}"

# Shift the positional parameters to the left
shift

# Loop through each remaining argument provided to the script
for hook in "$@"; do
    # Source the file corresponding to each argument with the flag as a suffix
    source "${HOME}/.dotfiles/hooks/${hook}.${flag}"
done
