#!/usr/bin/env zsh
emulate zsh -C

# -- color codes --
PURPLE_LIGHT="\033[1;35m"
PURPLE="\033[1;35m"
ORANGE="\033[1;33m"
GREEN="\033[1;32m"
CYAN="\033[1;36m"
BLUE="\033[1;34m"
RED="\033[1;31m"
HUE_OFF="\033[0m"

function zurbo() {
  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    cat << \
EOF
${CYAN}Usage:${HUE_OFF}
  ${CYAN}zurbo${RESET} [wait_time] [ice1] [ice2] ... [plugin]

${CYAN}Info:${HUE_OFF}
  Zurbo enhances Zinits plugin loading syntaxiproves syntax readability, and
  reduces syntax verbosity by adding a method to set default ICE modifiers.

${CYAN}ICE Defaults:${HUE_OFF}}
  ${CYAN}lucid, light-mode, wait"0".

${CYAN}Environment Variables:${HUE_OFF}
  ${CYAN} ZINIT_ICE_DEFAULTS: A list of ICE modifiers to set as default
EOF
  return

  if [[ "$1" =~ ^[0-9]+$ ]]; then
    wait_time="$1"
    shift
  else
    wait_time="0"        # Set the wait time to the first argument
    shift                         # Remove the first argument
  fi

  local plugin="${*: -1}" # Get the last argument

  local ices=()                  # Initialize an empty array
  for ((i = 1; i < $#; i++)); do # Loop over all arguments except the last one
    ices+=("${!i}")              # Add the argument to the ices array
  done

  local id="${plugin#*/}" # Get the repository name by removing the username

  # Use the ZINIT_ICE_DEFAULTS environment variable if it's set, otherwise use an empty string
  local additional_ices="${ZINIT_ICE_DEFAULTS:-}"

  zinit ice lucid light-mode wait"$wait_time" id"$id" $additional_ices "${ices[@]}"
  zinit load "$plugin"
}
