#!/usr/bin/env zsh

emulate zsh -C

# -- COLOR codes --
PURPLE="\033[1;35m"
GREEN="\033[1;32m"
CYAN="\033[1;36m"
BLUE="\033[1;34m"
RED="\033[1;31m"
OFF="\033[0m"
function zurbo() {
  [[ "$1" == "-h" || "$1" == "--help" ]] &&
    echo -e "\
      ${PURPLE}Usage:$OFF\n
      ${ORANGE}zurbo [WAIT_TIME] [ICE1] [ICE2] ... [PLUGIN]$OFF\n
      ${PURPLE}Info:$OFF\n
      Zurbo is a Zinits plugin load wraper that adds ease-of-life features,\n
      decreases code verbosity, increases syntax readbility, and lowers the\n
      overall plugin loading time by enabling turbo and light-mode while at\n
      the same time disabling reporting and parsing out the github account\n
      name, so only the repo name is used for the plugin. Additionally, a\n
      new env-var is available to customize the ICE defaults to your needs.\n
      ${PURPLE}ICE Defaults:$OFF\n
      lucid, light-mode, wait'0'\n
      ${PURPLE}Environment Variables:$OFF\n
      ZINIT_ICE_DEFAULTS: List of Ices." && return

  [[ "$1" =~ ^[0-9]+$ ]] && wait_time="$1" && shift || wait_time="0"

  local PLUGIN="${*: -1}"
  ICES=()
  local PLUGIN_ID="${PLUGIN#*/}"
  local ATLOAD_HOOK_ICE=""

  for arg in "$@"; do
    if [[ "$arg" == "atload_hook" ]]; then
      ATLOAD_HOOK_ICE=atload="hook ${PLUGIN_ID}.atload.zsh"
    elif [[ "$arg" == "atinit_hook" ]]; then
      ATINIT_HOOK_ICE=atinit="hook ${PLUGIN_ID}.atinit.zsh"
    elif [[ "$arg" == "gh" ]]; then
      ICES+=("as\"program\"" "from\"gh-r\"")
    else
      ICES+=("$arg")
    fi
  done

  zinit for lucid light-mode wait"$wait_time" id-as"$PLUGIN_ID" $ATLOAD_HOOK_ICE $ATINIT_HOOK_ICE "${ICES[@]}" "$PLUGIN"
}
