#!/usr/local/bin/bash


# Get the project-endpoint by project name and environment args
# $1= project name
# $2= Environment <PRODUCTION, PrePRODUCTION, PLAYGROUND>

string="Build the string"

idps-sanity_check(){
  string="https://$(1)/porticor-sec/get_instance_status?serial=$(2)"
  curl $string
}


