#!/bin/bash
# vim: set filetype=sh :
# ------------------------------------------------------------------------------
# Name    : aliases
# About   : Contains user aliases and functions
# Author  : Andrew Kuttor
# Contact : andrew.kuttor@gmail.com
# ------------------------------------------------------------------------------
#alias vi="nim"
alias ansible-create="nsible-galaxy init  --offline --force "
alias ak="tree -C"
alias cp="cp -ri"
alias df="df -hi"
alias diff="colordiff -ru"
alias dog="pygmentize -O style=monokai -f console256 -g"
alias doit="source !:1"
alias du="du -csh"
alias free="free -mt"
alias h="history"
alias hu="h|rg "
alias l="exa -a1 --group-directories-first "
alias ld="gls -d "
alias ll="exa -mFhlai --git --group-directories-first "
alias mkdir="mkdir -pv"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias nv="nvim"
alias path='echo $PATH | tr -s ":" "\n"'
alias pcat="pygmentize -f terminal256 -O style=monokai -g"
alias pip-upgrade="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U"
alias ports="netstat -lantip"
alias quit="exit"
alias reload="exec $SHELL -l"
alias rm="rm -ii"
alias sudo="sudo "
alias vim="mvim -v"
alias whichi-all="type -all"
