#!/bin/bash

# ------------------------------------------------------------------------------
# Name    : aliases
# About   : Contains user aliases and functions
# Author  : Andrew Kuttor
# Contact : andrew.kuttor@gmail.com
# ------------------------------------------------------------------------------


# Aliases
alias pip-upgrade="pip freeze --local | grep -v '^\-e' |\
cut -d = -f 1  | s pip install --user"
alias path='echo $PATH | tr -s ":" "\n"'  # Pretty print $PATH
alias quit='exit'
alias which='type -all'
alias mkdir="mkdir -pv"
alias df='df -hi'
alias du='du -csh'
alias cp="cp -ri" 
alias free='free -mt'
alias rm='rm -ii'
alias diff="colordiff -ru"
alias ll="gls -mFhlai --color --group-directories-first "
alias ld="gls -d "
alias l="gls -a1 --color --group-directories-first "
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias path='echo $PATH | tr -s ":" "\n"'
alias ports='netstat -lantip'
alias sudo='sudo '
alias reload="exec $SHELL -l"
alias h="history"
alias hu="h|rg "
alias nv="nvim"
alias vim="nvim"
alias vi="nim"
alias ak="tree -Csuh"
