#!/usr/bin/env zsh

# Zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

zmodload -i zsh/complist

zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path ~/.zsh/cache/$HOST

zstyle ':completion:*' completer _complete _correct _approximate
zstyle ':completion:*' glob on
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle :compinstall filename ~/.zshrc

zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin

autoload -U compinit
compinit

# Awless completion
source /usr/local/share/zsh/site-functions/_awless
