#! /bin/bash

# ------------------------------------------------------------------------------
# Name    : bashrc
# About   : Extended usercode/configurations for Bash
# Author  : Andrew Kuttor
# Contact : andrew.kuttor@gmail.com
# ------------------------------------------------------------------------------

# Vars
DOTS=$HOME/.dotfiles

# Language
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Editor
export EDITOR="vim"

# Colors
export CLICOLOR=1

# Hub
eval "$(hub alias -s)"

# FZF
# FZF
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Colored Man pages
man() {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    man "$@"
}

# Completins
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
if [ -d /usr/local/etc/bash_completion.d ]; then
  for file in /usr/local/etc/bash_completion.d/*; do
    . $file
  done
fi


# Builtins
shopt -s autocd          # Auto execute CD
#shopt -s nocaseglob      # Case in-sensitive globbing
shopt -s cdspell         # Autocorrect arguments in cd
shopt -s dirspell        # Autocorrect directory name
shopt -s checkwinsize    # Checks window size per command
shopt -s progcomp        # Programmable completions
shopt -s expand_aliases  # Expands aliases
shopt -s histappend      # Append to history file, don't overwrite
shopt -s histreedit      # Edit history after failed sub
shopt -s histverify      # Verify expansion before execute

# Sources
[[ -f "$DOTS/functions" ]] && . $DOTS/functions
[[ -f "$DOTS/aliases" ]] && . $DOTS/aliases
[[ -f "$DOTS/history" ]] && . $DOTS/history
[[ -f "$DOTS/completions" ]] && . $DOTS/completions 

# prompt
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
  source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi

