#! /bin/bash

# ------------------------------------------------------------------------------
# Name    : bashrc
# About   : Extended usercode/configurations for Bash
# Author  : Andrew Kuttor
# Contact : andrew.kuttor@gmail.com
# ------------------------------------------------------------------------------

# Vars
DOTS=$HOME/.dotfiles


# Editor
export EDITOR="vim"

# For Windows Molecule testing
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] &&\
    . /usr/local/etc/profile.d/autojump.sh


# fzf
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
[ -f $HOME/.fzf.bash ] && source $HOME/.fzf.bash

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

# Colors
export CLICOLOR=1

# Hub
eval "$(hub alias -s)"

# Colored Man pages
man() {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    man "$@"
}

# Completions
#[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
#if [ -d /usr/local/etc/bash_completion.d ]; then
#  for file in /usr/local/etc/bash_completion.d/*; do
#    . $file
#  done
#fi

if [ -f `brew --prefix`/etc/bash_completion.d/git-completion.bash ]; then
  . `brew --prefix`/etc/bash_completion.d/git-completion.bash
fi

# Builtins
shopt -s autocd          # Auto execute CD
#shopt -s nocaseglob      # Case in-sensitive globbing
shopt -s cdspell         # Autocorrect arguments in cd
shopt -s dirspell        # Autocorrect directory name
shopt -s checkwinsize    # Checks window size per command
shopt -s progcomp        # Programmable completions
shopt -s expand_aliases  # Expands aliases
shopt -s histappend      # Append to history file, don't overwrite
shopt -s histreedit      # Edit history after failed sub
shopt -s histverify      # Verify expansion before execute

# Sources
[[ -f "$DOTS/functions" ]] && . $DOTS/functions
[[ -f "$DOTS/aliases" ]] && . $DOTS/aliases
[[ -f "$DOTS/history" ]] && . $DOTS/history
[[ -f "$DOTS/completions" ]] && . $DOTS/completions 

# prompt
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
  source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi
