#!/usr/bin/env zsh

#------------------------------------------------------------------------------
# History
#------------------------------------------------------------------------------

setopt BANG_HIST                    # '!' specially treated
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY             # "start;elapsed;command" format
setopt INC_APPEND_HISTORY           # Write immediately to file
setopt SHARE_HISTORY                # All sessions share history
setopt HIST_EXPIRE_DUPS_FIRST       # Duplicate entries expire first
setopt HIST_IGNORE_DUPS             # Don't record dupes
setopt HIST_IGNORE_ALL_DUPS         # If dupe, delete older entry
setopt HIST_FIND_NO_DUPS            # Do not display dupes
setopt HIST_IGNORE_SPACE            # Exclude entries started with space
setopt HIST_SAVE_NO_DUPS            # Dupes don't write to file
setopt HIST_REDUCE_BLANKS           # Remove blanks before being written
setopt HIST_VERIFY                  # Don't execute immediately
setopt HIST_BEEP                    # Beep!

# File path
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

