#! /bin/bash

# ------------------------------------------------------------------------------
# Name    : history
# About   : Extended history configurations for dotfiles
# Author  : Andrew Kuttor
# Contact : andrew.kuttor@gmail.com
# ------------------------------------------------------------------------------

# alias
alias h="history"

# export
export HISTSIZE=100000                               # History file size
export HISTFILESIZE=$HISTSIZE                        # History limit
export HISTCONTROL="ignoredups:erasedups"              # Ignore lead-space & dupes
export HISTTIMEFORMAT="[%F %T] "                     # Custom time format
export HISTIGNORE="ls:cd:exa:pwd:exit:history:clear" # Ignore recording commands

