#! /usr/bin/env bash

touch "$HOME/.hushlogin"

function install_homebrew {
  url=https://raw.githubusercontent.com/Homebrew/install/master/install.sh

  echo Installing Homebrew if it is missing
  if [[ ! -d /usr/local/bin/brew ]]; then
    /bin/bash -c "$(curl -fsSL $url)"
  fi

  echo "Installing Brew Packages"
  /opt/homebrew/bin/brew bundle install \
    --file=$HOME/.dotfiles/Brewfile
}

function install_zinit() {
  url=https://git.io/zinit-install

  echo Running the Zinit installer
  if [[ ! -d "$HOME/.zinit" ]]; then
    mkdir "$HOME/.zinit"
    sh -c "$(curl -fsSL $url)"
  fi
}

function configure_neovim() {
  echo 'Configuring NeoVim using "The Lean Mean NeoVim Config"'
  mkdir ~/.config
  git clone git://github.com/rafi/vim-config.git ~/.config/nvim
  cd ~/.config/nvim || exit
  ln -fs ~/.config/nvim ~/.vim
}

function create_zlocalrc() {
  echo "Creating local config file .zlocalrc"
  if [[ ! -e $HOME/.zlocalrc ]]; then
    touch "$HOME/.zlocalrc"
  fi
}

install_homebrew
install_zinit
create_zlocalrc
