#! /usr/bin/env bash

touch "$HOME/.hushlogin"

function install_homebrew {
  url=https://raw.githubusercontent.com/Homebrew/install/master/install.sh

  echo Installing Homebrew if it is missing
  if [[ ! -d /usr/local/bin/brew ]]; then
    /bin/bash -c "$(curl -fsSL $url)"
  fi

  echo "Installing Brew Packages"
  /opt/homebrew/bin/brew bundle install \
    --file=$HOME/.dotfiles/Brewfile
}

function install_zinit() {
  url=https://git.io/zinit-install

  echo Running the Zinit installer
  if [[ ! -d "$HOME/.zinit" ]]; then
    mkdir "$HOME/.zinit"
    sh -c "$(curl -fsSL $url)"
  fi
}

function simlink_configs() {
  configs=(editorconfig gitconfig gitignore inputrc ripgreprc)
  echo "Simlinking configs to home"
  configs=(editorconfig gitconfig gitignore inputrc ripgreprc)
  for config in "${configs[@]}"; do
    ln -fs "$HOME/.dotfiles/configs/$config" "$HOME/.$config"
  done
}

function configure_neovim() {
  echo 'Configuring NeoVim using "The Lean Mean NeoVim Config"'
  mkdir ~/.config
  git clone git://github.com/rafi/vim-config.git ~/.config/nvim
  cd ~/.config/nvim || exit
  ln -fs ~/.config/nvim ~/.vim
}

function simlink_zfiles() {
  echo "Simlinking core ZSH files to home. Will overwrite any current zsh rc's"
  files=(zshrc zshenv zprofile)
  for file in "${files[@]}"; do
    ln -fs "$HOME/.dotfiles/zsh/$file" "$HOME/.$file"
  done
}

install_homebrew
install_zinit
simlink_configs
simlink_zfiles
