#! /usr/bin/env bash

touch "$HOME/.hushlogin"
function install_homebrew {
    echo Installing Homebrew if it is missing

    if [[ ! -d /usr/local/bin/brew ]]; then
        url=https://raw.githubusercontent.com/Homebrew/install/master/install.sh
        /bin/bash -c "$(curl -fsSL $url)"
    fi

    echo "Installing Brew Packages"
    cd $DOTFILES
    brew bundle
}

function install_zinit() {
  echo Running the Zinit installer
  if [[ ! -d "$HOME/.zinit" ]]; then
    mkdir $HOME/.zinit
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/master/doc/install.sh)"
  fi
}

function simlink_configs() {
  echo "Simlinking configs to home"
  configs=(editorconfig gitconfig gitignore inputrc ripgreprc)
  for config in $configs; do
    ln -s $config $HOME/.$config
  done
}

function configure_neovim() {
  echo 'Configuring NeoVim using "The Lean Mean NeoVim Config"'
  mkdir ~/.config
  git clone git://github.com/rafi/vim-config.git ~/.config/nvim
  cd ~/.config/nvim
  ln -s ~/.config/nvim ~/.vim
}

function simlink_zfiles() {
  echo "Simlinking core ZSH files to home. Will overwrite any current zsh rc's"
  files=(zshrc zshenv zprofile)

  for file in files; do
    ln -s $HOME/.dotfiles/$file $HOME/.$file
  done
}

function update_terminfo() {
  echo "Creating custom terminfo file add italics"
  tic $HOME/.dotfiles/config/xterm-256color.terminfo
}

install_homebrew
install_zinit
simlink_configs
configure_neovim
simlink_zfiles
update_terminfo


