#!/usr/bin/env zsh

# Author: Andrew Kuttor
# E-mail: andrew_kuttor@intuit.com

# ==============================================================================
# Key Bindings
# ==============================================================================

bindkey -e

bindkey "^H"        delete-word # iterm
bindkey "^[[3~"     delete-char # tmux

bindkey "^[[1;9D"   backward-word # iterm
bindkey "^[^[[D"    backward-word # tmux osx
bindkey "^[[1;3D"   backward-word # tmux ubuntu

bindkey "^[[1;9C"   forward-word # iterm
bindkey "^[^[[C"    forward-word # tmux osx
bindkey "^[[1;3C"   forward-word # tmux ubuntu

bindkey "^[[H"      beginning-of-line # iterm
bindkey "^[[1~"     beginning-of-line # tmux

bindkey "^[[F"      end-of-line # iterm
bindkey "^[[4~"     end-of-line # tmux
