#!/usr/bin/env zsh

# In menu completion, the Return key will accept the current selected match
# bindkey -M menuselect '^M' .accept-line

# shift-tab : go backward in menu (invert of tab)
bindkey '^[[Z' reverse-menu-complete

# alt-x : insert last command result
zmodload -i zsh/parameter
insert-last-command-output() {
  LBUFFER+="$(eval $history[$((HISTCMD-1))])"
}
zle -N insert-last-command-output
bindkey '^[x' insert-last-command-output

# FASD
bindkey '^X^A' fasd-complete    # C-x C-a to do fasd-complete (fils and directories)
bindkey '^X^F' fasd-complete-f  # C-x C-f to do fasd-complete-f (only files)
bindkey '^X^D' fasd-complete-d  # C-x C-d to do fasd-complete-d (only directories)

# Attempt shell expansion on the current word up to cursor.
# Do not re-bind key if fzf completion has been loaded before.
if [[ $(bindkey '^I') != *fzf-completion ]]; then
  bindkey '^I'             expand-or-complete-prefix     # Tab
fi

# Perform history expansion and insert a space into the buffer. This is intended to be bound to SPACE.
bindkey ' '                magic-space
bindkey -M menuselect '^^' accept-and-infer-next-history # Ctrl + Return
bindkey -M menuselect '^Z' undo                          # Ctrl + Z
bindkey -M menuselect '\e' send-break                    # ESC
bindkey -M menuselect '^C' send-break                    # Ctrl + C
bindkey -M menuselect '^I' magic-space                   # Tab
bindkey -M menuselect ' '  magic-space

