#!/usr/local/bin/zsh
# File: setoptions
# Info: Zsh configuration file for setopt directives
# -----------------------------------------------------------------------------

setopt always_last_prompt
setopt always_to_end
setopt auto_cd
setopt auto_menu
setopt auto_param_keys
setopt auto_param_slash
setopt auto_pushd
setopt complete_aliases
setopt complete_in_word
setopt correct
setopt extendedglob
setopt globdots
setopt hash_list_all
setopt interactive_comments
setopt list_ambiguous
setopt list_types
setopt local_options
setopt magic_equal_subst
setopt noflowcontrol
setopt nohup
setopt nonomatch
setopt notify
setopt prompt_subst
setopt shwordsplit
