#!/usr/local/bin/zsh
# File: setoptions
# Info: Zsh configuration file for setopt directives
# -----------------------------------------------------------------------------

setopt ALWAYS_LAST_PROMPT
setopt ALWAYS_TO_END
setopt APPEND_HISTORY
setopt AUTO_CD
setopt AUTO_MENU
setopt AUTO_PARAM_KEYS
setopt AUTO_PARAM_SLASH
setopt AUTO_PUSHD
setopt COMPLETE_ALIASES
setopt COMPLETE_IN_WORD
setopt CORRECT
setopt EXTENDEDGLOB
setopt EXTENDED_HISTORY
setopt GLOB_DOTS
setopt HASH_LIST_ALL
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt INTERACTIVE_COMMENTS
setopt LIST_AMBIGUOUS
setopt LIST_TYPES
setopt LOCAL_OPTIONS
setopt MAGIC_EQUAL_SUBST
setopt NOFLOWCONTROL
setopt NOHUP
setopt NONOMATCH
setopt NOTIFY
setopt PROMPT_SUBST
setopt SHARE_HISTORY
setopt SHWORDSPLIT
unsetopt CASE_GLOB
