#!/usr/bin/env bash
# file: setup
# info: creates necessary links/files to setup dotfiles and install packages

# Homebrew
#/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Zinit
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"

# Brew
#/home/linuxbrew/.linuxbrew/bin/brew bundle --force --file "$HOME/.dotfiles/Brewfile"

# Fonts
#nix_fonts="/usr/share/fonts"
#mac_fonts="$HOME/Library/Fonts"
#cp -R "$fonts" $nix_fonts

# disable welcome messages and disable : 
touch "$HOME/.hushlogin"

# Simlink misc confs
for FILE in `ls $CONFIGS`; do
    CONFIG=.$FILE
    ln -fs $CONFIGS/$FILE $HOME/$CONFIG
done

# Add main shell sources to zshrc file
cat << EOF >> $HOME/.zshrc

# Sources
source "$HOME/.dotfiles/zsh/zinit"
source "$HOME/.dotfiles/zsh/env"
source "$HOME/.dotfiles/zsh/setopts"
source "$HOME/.dotfiles/zsh/aliases"
source "$HOME/.dotfiles/zsh/completes"
source "$HOME/.dotfiles/zsh/keybind"

# Prompt
source "$HOME/.dotfiles/.p10k.zsh"

EOF




