#! /usr/bin/env bash
# file: setup
# info: creates necessary links/files to setup dotfiles and install packages

if [ "$OSTYPE" == "linux-android" ]; then
    echo "Installing pkg based dependencies..."
    pkg install -y git ruby curl clang proot make exa fd exa ripgrep
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else [[ "$OSTYPE" == "dawrin*" ]]
    echo "Installing Homebrew for MacOS"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    brew bundle Brewfile && brew bundle Caskfile
    echo "Copying fonts to /Library/Fonts" && cp fonts /Library/Fonts
fi

echo "Installing Zinit for Zshell"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"

echo "Making .hushlogin file in $HOME"
touch "$HOME/.hushlogin"

echo "Simlinking cpmfog rbfee"
for FILE in "$HOME"/.dotiles/configs/*
do
    ln -fs "$HOME"/.dotfiles/configs/"$FILE" "$HOME"/."$FILE"
done

echo "main shell sources to zshrc file"
cat << EOF >> "$HOME"/.zshrc

# Source main Dotfiles
source "$HOME/.dotfiles/zsh/zinit"
source "$HOME/.dotfiles/zsh/env"
source "$HOME/.dotfiles/zsh/aliases"
source "$HOME/.dotfiles/zsh/completes"
source "$HOME/.dotfiles/zsh/keybind"
EOF