#! /usr/bin/env zsh
# file: setup
# info: creates necessary links/files to setup dotfiles and install packages

DOTFILES="${0%/*}"

if [[ ! -f $ZINIT_HOME/bin/zinit.zsh ]]; then
	git clone https://github.com/psprint/zinit $ZINIT_HOME/bin
	zcompile $ZINIT_HOME/bin/zinit.zsh
fi


echo "Making .hushlogin file in $HOME"
touch "$HOME/.hushlogin"


echo "Simlinking cpmfog rbfee"
for FILE in "$HOME"/.dotiles/configs/*
do
    ln -fs "$HOME"/.dotfiles/configs/"$FILE" "$HOME"/."$FILE"
done

echo "main shell sources to zshrc file"
cat << EOF >> "$HOME"/.zshrc

# Source main Dotfiles
source "$HOME/.dotfiles/zsh/zinit"
source "$HOME/.dotfiles/zsh/env"
source "$HOME/.dotfiles/zsh/aliases"
source "$HOME/.dotfiles/zsh/completes"
source "$HOME/.dotfiles/zsh/keybind"
EOF
