#!/usr/bin/env zsh

#============================================================================
# Initialize Zplug
#============================================================================

# If check fails clone it
[[ ! -d $ZPLUG_HOME ]] && \
    git clone "https://github.com/b4b4r07/zplug" $ZPLUG_HOME

# Initialize
source "$ZPLUG_HOME/init.zsh"

#============================================================================
# Specify Plugins
#============================================================================

# Selfless
zplug "zplug/zplug", hook-build:"zplug --self-manage"

zplug "joel-porquet/zsh-dircolors-solarized.git"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:3
zplug "mafredri/zsh-async", from:github
zplug "sindresorhus/pure", use:pure.zsh, defer:3, as:theme
zplug "fabiokiatkowski/exercism.plugin.zsh"
zplug "plugins/git", from:oh-my-zsh, defer:3, if:"which git"
zplug "plugins/gitfast", from:oh-my-zsh
zplug "plugins/git-extras", from:oh-my-zsh
zplug "plugins/github", from:oh-my-zsh
zplug "plugins/jsontools", from:oh-my-zsh
zplug "plugins/python", from:oh-my-zsh
zplug "plugins/ruby", from:oh-my-zsh
zplug "plugins/pip", from:oh-my-zsh
zplug "plugins/autopep8", from:oh-my-zsh
zplug "plugins/web-search", from:oh-my-zsh
zplug "plugins/fasd", from:oh-my-zsh
zplug "plugins/compleat", from:oh-my-zsh
zplug "plugins/aws", from:oh-my-zsh
zplug "plugins/command-not-found", from:oh-my-zsh
zplug 'plugins/sudo', from:oh-my-zsh, \
    ignore:oh-my-zsh.sh, if:"(($+commands[sudo]))"
zplug "sindresorhus/pretty-time-zsh", from:github
zplug "gko/ssh-connect"
zplug "glidenote/hub-zsh-completion"
zplug "Valodim/zsh-curl-completion"
zplug "srijanshetty/zsh-pip-completion"
zplug "jamesob/desk", from:github, as:command, use:"desk"
zplug "zuxfoucault/colored-man-pages_mod", from:oh-my-zsh
zplug 'b4b4r07/epoch-cat', as:command, hook-build:'go get -d && go build'
zplug "b4b4r07/zplug-doctor", lazy:yes
zplug "b4b4r07/zplug-cd", lazy:yes
zplug "b4b4r07/zplug-rm", lazy:yes
zplug "b4b4r07/open-link.sh", as:command, use:'(*).bash', rename-to:'$1'
zplug "b4b4r07/zsh-gomi", as:command, use:bin/gomi
zplug "b4b4r07/ssh-keyreg", as:command, use:bin
zplug 'b4b4r07/copy', as:command, use:'(*).sh', rename-to:'$1'
zplug 'lib/completion', from:oh-my-zsh
zplug 'lib/functions', from:oh-my-zsh
zplug 'lib/history', from:oh-my-zsh
zplug 'lib/key-bindings', from:oh-my-zsh
zplug 'lib/misc', from:oh-my-zsh
zplug 'lib/spectrum', from:oh-my-zsh
zplug 'lib/theme-and-appearance', from:oh-my-zsh
zplug 'mutantcornholio/prok', as:command, use:'(*).sh', rename-to:'$1'
zplug "stedolan/jq", as:command, from:gh-r, rename-to:jq
zplug "jhawthorn/fzy", as:command, hook-build:"make && sudo make install"
zplug "chrissicool/zsh-bash"

#============================================================================
# Initialize Plugins
#===========================================================================

# If plugin non-exists, install it
zplug check --verbose || zplug install

# Load plugins
zplug load
