#!/usr/local/bin/zsh
# Name: Andrew Kuttor
# Mail: andrew.kuttor@gmail.com

# -----------------------------------------------------------------------------
# misc
# -----------------------------------------------------------------------------

# Sane terms
stty start undef
stty stop undef

# Options
export ZPLUG_HOME="$HOME/.zplug"
export ZPLUG_INIT="$ZPLUG_HOME/init.zsh"
export LOCAL="/usr/local"
export DOTS="$HOME/.dotfiles"
export EDITOR=`which vim`
export VISUAL="$EDITOR"
export skip_global_compinit=1

# Language
export LANGUAGE="en_US.UTF-8"
export LANG="${LANGUAGE}"
export LC_ALL="${LANGUAGE}"
export LC_CTYPE="${LANGUAGE}"

# LS Coloring
unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1

# ZSH Autosuggestion theme configuration
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=243'

# Editor
export EDITOR=vim
export CVSEDITOR="${EDITOR}"
export SVN_EDITOR="${EDITOR}"
export GIT_EDITOR="${EDITOR}"

# Pager
export PAGER=less

# Less status line
export LESS='-R -f -X -i -P ?f%f:(stdin). ?lb%lb?L/%L.. [?eEOF:?pb%pb\%..]'
export LESSCHARSET='utf-8'

# LESS man page colors (makes Man pages more readable).
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[00;44;37m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Files created by root can be +RX by owners who are users or groups.
umask 027

# Initialize the $PATH ARRAY
path+=(
  $HOME/bin
  $HOME/sbin
  $LOCAL/sbin
  $LOCAL/bin
  $LOCAL/Cellar
  $PYTHON/2.7/bin
  $HOME/.fzf/bin
)
typeset -U PATH path

export FZF_SHELL="/usr/local/Cellar/fzf/0.17.5/shell"

source fzf.zsh
source "$FZF_SHELL/completion.zsh"
source "$FZF_SHELL/completion.zsh"

[[ $(command -v fasd) ]] &&\
    eval "$(fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install)"

# -----------------------------------------------------------------------------
# Sources
# -----------------------------------------------------------------------------

source "$DOTS/aliases"
source "$DOTS/functions"
source "$DOTS/zplugs"
source "$DOTS/setoptions"
source "$DOTS/history"
source "$DOTS/keybindings"
source "$DOTS/autoloads"