#! /usr/bin/env zsh

# Name: Andrew Kuttor
# Mail: andrew.kuttor@gmail.com

# One-Liner install for Oh My Zsh:
    # sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Sourcing thw Oh My Zshell goodness
source $ZSH/oh-my-zsh.sh

# Path additions
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH="/Users/yeti/.oh-my-zsh"
export PATH="/usr/local/opt/binutils/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"

# Shell Theme 
ZSH_THEME="robbyrussell"

# Little extras
COMPLETION_WAITING_DOTS="true"

# History Junk
setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks   # remove superfluous blanks from history items
setopt inc_append_history   # save history entries as soon as they are entered
setopt share_history        # Share the same history file between sessions
HIST_STAMPS="11/19/2018"
HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=4096

# Plugins
# Standard plugins: ~/.oh-my-zsh/plugins/*
# Custom plugins:  ~/.oh-my-zsh/custom/plugins/
plugins=(
  z
  fz
  git
  osx
  bash
  brew
  python
  gnu-utils
  zsh-autosuggestions
  fast-syntax-highlighting
  ansiblee
  vagrant
  vim
  zsh-syntax-highlighting
  async

)

# FASD
eval "$(fasd --init auto)"



# Language setting
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Custom Aliases
source $HOME/.dotfiles/aliases

# Custom Functions
source $HOME/.dotfiles/functions

# From http://dotfiles.org/~_why/.zshrc
# Sets the window title nicely no matter where you are
function title() {
  # escape '%' chars in $1, make nonprintables visible
  a=${(V)1//\%/\%\%}

  # Truncate command, and join lines.
  a=$(print -Pn "%40>...>$a" | tr -d "\n")

  case $TERM in
  screen)
    print -Pn "\ek$a:$3\e\\" # screen title (in ^A")
    ;;
  xterm*|rxvt)
    print -Pn "\e]2;$2\a" # plain xterm title ($3 for pwd)
    ;;
  esac
}
