#!/usr/bin/env zsh
# Custom config file for Zshell
# By: Andrew Kuttor

#============================================================================-
# Load the sources
#============================================================================

source "$ZDOTDIR/zoptions"
source "$ZDOTDIR/zplug"
source "$ZDOTDIR/zcompletes"
source "$ZDOTDIR/exports.zsh"
source "$ZDOTDIR/bindkeys.zsh"
source "$ZDOTDIR/aliases"
source "$ZDOTDIR/functions"
