#!/usr/bin/env zsh
# Custom config file for Zshell
# By: Andrew Kuttor

#============================================================================-
# Load the sources
#============================================================================

source "$ZDOTDIR/configs"
source "$ZDOTDIR/zplug"
source "$ZDOTDIR/completions"
source "$ZDOTDIR/keybindings"
source "$ZDOTDIR/aliases_shell"
source "$ZDOTDIR/functions"
