brew "brew-cask-completion"
brew 'coreutils'
brew 'jq'
brew 'xz'
brew 'hg'
brew 'fzf'
brew 'lsd'
brew 'eza'
brew 'lua'
brew 'gawk'
brew 'grep'
brew 'gsed'
brew 'wget'
brew 'curl'
brew 'tmux'
















