#! /usr/bin/env zsh
# Remove spurious find error messages on access restrictions.
# Keeps find'sb noutput clean, tidy and easier to read.
# Source: https://apple.stackexchange.com/a/353650  

{ LC_ALL=C command gfind "$@" 3>&2 2>&1 1>&3 | \
  grep -v -e 'Permission denied' -e 'Operation not permitted' >&3; \
  [ $? = 1 ]; \
} 3>&2 2>&1
