#!/usr/bin/env sh

# you're so pretty
--pretty

# Search hidden files and directories.
--hidden

# Follow symbolic links.
--follow

# Because who cares about case!?
--smart-case

# Sort by file path.
--sort=path

# ...but not inside .git directories
--glob=!.git/*

# Mimic ag's color output:
--colors=line:fg:yellow
--colors=line:style:bold
--colors=path:fg:green
--colors=path:style:bold
--colors=match:fg:black
--colors=match:bg:yellow
--colors=match:style:nobold

# Don't let ripgrep vomit really long lines to my terminal, and show a preview.
--max-columns=250
--max-columns-preview

# Files/folders to ignore
--glob=!**/*.js.map
--glob=!**/__snapshots__/*
--glob=!**/bin/*
--glob=!**/node_modules/*
--glob=!*.min.*
--glob=!.DS_Store
--glob=!.cache/*
--glob=!.config/htop
--glob=!.git/*
--glob=!Library/*
--glob=!Movies/*
--glob=!build*
--glob=!tags
--glob=!tmp/*
--glob=!vendor/*
