#!/usr/bin/env sh

# you're so pretty
--pretty

# search hidden files and directories.
--hidden

# follow symbolic links.
--follow

# because who cares about case!?
--smart-case

# Sort by file path.
--sort=path

# report match count
--count

# permit match to cross multiple lines
--multiline

# don't let ripgrep vomit really long lines
--max-columns=150
--max-columns-preview

# add my 'web' type.
--type-add
web:*.{html,css,js}*

# Search compressed files (gzip, bzip2, lzma, xz, lz4, brotli, zstd). This is disabled by default.
--search-zip

# show line numbers
--line-number

# Mimic ag's color output:
--colors=line:fg:yellow
--colors=line:style:bold
--colors=path:fg:green
--colors=path:style:bold
--colors=match:fg:black
--colors=match:bg:yellow
--colors=match:style:nobold

# Files/folders to ignore
--glob=!**/*.js.map
--glob=!**/__snapshots__/*
--glob=!**/bin/*
--glob=!**/node_modules/*
--glob=!*.min.*
--glob=!.DS_Store
--glob=!.cache/*
--glob=!.config/htop
--glob=!.git/*
--glob=!Library/*
--glob=!Movies/*
--glob=!build*
--glob=!tags
--glob=!tmp/*
--glob=!vendor/*
