#!/usr/bin/env zsh
# Vim:set filetype=inputrc syntax=inputrc noexpandtab:
# File: /Users/akuttor/.dotfiles/configs/inputrc

# Source the system inputrc file
INCLUDE /etc/inputrc

# Enable eight-bit input and output
set input-meta on
set output-meta on

# Completion Colours
set colored-completion-prefix on
set colored-stats on

# Treat hypen and underscores as equivalent
set completion-map-case

# Do case-insensitive tab completion
set completion-ignore-case on

# Show 3 characters of the completion
set completion-prefix-display-length

# Number of completions to display without prompt
set completion-query-items 200

# Tilde expansion when Readline attempts word completion
set expand-tilde on

# display ‘*’ start of modified history lines
set mark-modified-lines on

# Mark symlinked directories with a trailing /
set mark-symlinked-directories on

# Match dotfiles
set match-hidden-files on

# do not page completions
set page-completions off

# Immediately display completion matches.
set show-all-if-ambiguous on

# show all completions if the word is not modified
set show-all-if-unmodified on

# Smartly complete when cursor is not at EOL
set skip-completed-text on

# Enable visible statistics for completion
set visible-stats on

# Quiet Mode
set bell-style none
set echo-control-characters off

# Enable bracketed paste mode
set vim-bracketed-paste on

# Enable eight-bit input and output
set input-meta on
set output-meta on

# Completion Colours
set colored-completion-prefix on
set colored-stats on

# Treat hypen and underscores as equivalent
set completion-map-case

# Do case-insensitive tab completion
set completion-ignore-case on

# Show 3 characters of the completion
set completion-prefix-display-length

# Number of completions to display without prompt
set completion-query-items 200

# Tilde expansion when Readline attempts word completion
set expand-tilde on

# display ‘*’ start of modified history lines
set mark-modified-lines on

# Mark symlinked directories with a trailing /
set mark-symlinked-directories on

# Match dotfiles
set match-hidden-files on

# do not page completions
set page-completions off

# Immediately display completion matches.
set show-all-if-ambiguous on

# show all completions if the word is not modified
set show-all-if-unmodified on

# Smartly complete when cursor is not at EOL
set skip-completed-text on #


# Enable visible statistics for completion
set visible-stats on

# Quiet Mode
set bell-style none
set echo-control-characters off

# Enable bracketed paste mode
set vim-bracketed-paste on
