#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# Name    : aliases
# About   : Contains user aliases and functions
# Author  : Andrew Kuttor
# Contact : andrew.kuttor@gmail.com
# ------------------------------------------------------------------------------

# List files
alias ak="tree -C"
alias ak1="tree -L 1 -Ccfhau --du --dirsfirst "
alias ak2="tree -L 2 -Ccfhau --du --dirsfirst "
alias ak3="tree -L 3 -Ccfhau --du --dirsfirst "

# Git
alias gs="git status"

alias ansible-create="ansible-galaxy init  --offline --force"
alias c="clear"
alias cat="bat"
alias clip="termux-clipboard-set"
alias code="code-insiders"
alias cp="cp -ri"
alias df="df -hi"
alias diff="meld"
alias du="du -csh"
alias dug="dig +nocmd any +multiline +noall +answer     "
alias fpath='echo $fpath | tr -s " " "\n"'
alias free="free -mt"
alias fzf-preview="fzf --preview bat --style=numbers --color=always {} | head -500"
alias g="git"
alias grep="rg"
alias h="fh"
alias how="howdoi --color --all"
alias httpHeaders="curl -I -L"
alias hu="history | rg -i $"
alias l="exa -1 --color=always --group-directories-first --all"
alias lg="lazygit"
alias ll="exa --binary --group --header --all --long --links --inode --classify --blocks --group-directories-first"
alias ls="exa --git --color=always --group-directories-first"
alias mkdir="mkdir -pv"
alias molecule-create="molecule init scenario -r "
alias mtop="htop --sort-key=PERCENT_MEM"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias path='echo $PATH | tr -s ":" "\n"'
alias pip='pip3'
alias python='python3'
alias python-library="python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'"
alias quit="exit"
alias restart='reset; exec sudo --login --user $USER'
alias ssh="TERM=xterm-256color ssh"
alias sudo="sudo "
alias tf="terraform"
alias top-ten='print -l -- ${(o)history%% *} | uniq -c | sort -nr | head -n 10'
alias vi="nvim"
alias vim="nvim"
alias vimswap_clean='rm -rf $VIM_SWAP/*'
alias vscode_settings='HOME/Library/Application\ Support/Code/User/settings.json'
alias zb="z -b"
alias zf="z -I"
alias zi="z -i"
alias zi="zinit"
alias zmv="noglob zmv -W"
alias zz="z -c"
