#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# vim:set ft=zsh ts=2 sw=2 sts=0 foldmethod=marker:

# bash completions
autoload bashcompinit && bashcompinit

# Enable completions
autoload -Uz compinit && compinit

# Menu-like autocompletion selection
zmodload -i zsh/complist

# case insensitive path-completion
zstyle ':completion:*' matcher-list                       \
'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'             \
'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' \
'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' \
'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

# partial completion suggestions
zstyle ':completion:*'                list-suffixes
zstyle ':completion:*'                expand prefix suffix

# speedup path completion
zstyle ':completion:*'                accept-exact '*(N)'
zstyle ':completion:*'                use-cache on
zstyle ':completion:*'                cache-path ${CACHE}/zsh
zstyle ':completion:*'                use-perl on

# colors
zstyle ':completion:*:default'        list-colors '${(s.:.)LS_COLORS}'

# manuals
zstyle ':completion:*:manuals'        separate-sections true
zstyle ':completion:*:manuals.(^1*)'  insert-sections   true
zstyle ':completion:*:man:*'          menu yes select

# Fuzzy match mistyped completions.
zstyle ':completion:*'                completer _complete _list _match _approximate
zstyle ':completion:*:match:*'        original only
zstyle ':completion:*:approximate:*'  max-errors 1 numeric

# Don't complete unavailable commands.
zstyle ':completion:*:functions'      ignored-patterns '(_*|pre(cmd|exec))'

# Array completion element sorting.
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters

# Automatically find new executables in path
zstyle ':completion:*'                 rehash true

# Man
zstyle ':completion:*:manuals'         separate-sections true
zstyle ':completion:*:manuals.(^1*)'   insert-sections true

# Completion Style
zstyle ':completion:*:*:cd:*'          ignore-parents parent pwd
zstyle ':completion:*:*:cd:*'          tag-order local-directories directory-stack path-directories
zstyle ':completion:*:*:cd:*'          menu yes select

# Avoid twice the same element on rm
zstyle ':completion:*:rm:*'            ignore-line yes

# Insert all expansions for expand completer
zstyle ':completion:*:expand:*'        tag-order all-expansions

# History
zstyle ':completion:*:history-words'   list false
zstyle ':completion:*:history-words'   menu yes
zstyle ':completion:*:history-words'   remove-all-dups yes
zstyle ':completion:*:history-words'   stop yes