#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# vim:set ft=zsh ts=2 sw=2 sts=0 foldmethod=marker:

# file: bindkey
# info: Main config file for keybindings

# -----------------------------------------------------------------------------
# Keybinds
# -----------------------------------------------------------------------------

# Emacs
bindkey -e

bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

# Quote pasted URLs#
autoload -Uz history-search-end
autoload -Uz is-at-least
autoload -U url-quote-magic
autoload -U select-word-style
autoload -U edit-command-line
autoload -Uz colors && colors
autoload -U parseopts
autoload -U zargs
autoload -U zcalc
autoload -U zed
autoload -U zmv

zle -N edit-command-line
zle -N expand-or-complete-with-dots
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
zle -N insert-last-command-output
zle -N select-word-style bash
zle -N self-insert url-quote-magic
zle -N autosuggest-accept

bindkey " "       magic-space
bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word
bindkey "^[[F"    end-of-line
bindkey "^[[H"    beginning-of-line
bindkey '^ '      autosuggest-accept
bindkey "^E"      edit-command-line
bindkey "^I"      expand-or-complete-with-dots
bindkey "^N"      history-beginning-search-forward-end
bindkey "^P"      history-beginning-search-backward-end
bindkey "^X^L"    insert-last-command-output
