#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# vim:set ft=zsh ts=2 sw=2 sts=0 foldmethod=marker:

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

autoload -U +X bashcompinit && bashcompinit

autoload -Uz colors && colors


zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

autoload -Uz history-search-end
autoload -Uz is-at-least
autoload -U select-word-style
autoload -U edit-command-line
autoload -U \
    parseopts \
    zargs \
    zcalc \
    zed \
    zmv \

zle -N edit-command-line

zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
zle -N insert-last-command-output
zle -N select-word-style bash
zle -N autosuggest-accept

# Emacs
bindkey -e

bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

bindkey " " magic-space
bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word
bindkey "^[[F" end-of-line
bindkey "^[[H" beginning-of-line
bindkey '^ ' autosuggest-accept
bindkey "^E" edit-command-line

bindkey "^N" history-beginning-search-forward-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^X^L" insert-last-command-output
