#!/usr/bin/env zsh

# Autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=136'
ZSH_AUTOSUGGEST_CLEAR_WIDGETS=(do_enter kill-line $ZSH_AUTOSUGGEST_CLEAR_WIDGETS)

# History
HISTFILE="$HOME/.zhistory"
HISTSIZE=10000000
SAVEHIST=10000000
