#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# vim: set sts=2 sw=2 ts=2

skip_global_compinit="1"

# powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# zsh-autopair
zinit ice wait lucid; zinit load hlissner/zsh-autopair

# Oh-My-zShell
zplugin snippet OMZ::lib/clipboard.zsh
zplugin snippet OMZ::lib/compfix.zsh
zplugin snippet OMZ::lib/completion.zsh
zplugin snippet OMZ::lib/correction.zsh
zplugin snippet OMZ::lib/directories.zsh
zplugin snippet OMZ::lib/functions.zsh
zplugin snippet OMZ::lib/git.zsh
zplugin snippet OMZ::lib/grep.zsh
zplugin snippet OMZ::lib/history.zsh
zplugin snippet OMZ::lib/key-bindings.zsh
zplugin snippet OMZ::lib/spectrum.zsh
zplugin snippet OMZ::lib/termsupport.zsh

# FZF, FZ, Z
zinit ice wait lucid; zinit light Aloxaf/fzf-tab

# z tab completion
zinit ice wait lucid; zinit light changyuheng/fz

# z / fzf (ctrl-g)
zinit ice wait lucid; zinit light andrewferrier/fzf-z

# z.lua
zinit ice wait lucid; zinit light skywind3000/z.lua

# Turbo-enabled CompDefs
autoload -Uz compinit && compinit
zinit cdreplay -q
