#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# vim:set ft=zsh ts=2 sw=2 sts=0 foldmethod=marker

# file: zplugin
# info: Zplugin configuration

# Zplugin init
source "${HOME}/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

# Compinit speed up loading
ZPLGM[COMPINIT_OPTS]=-C

# Theme: Spaceship
zplugin light denysdovhan/spaceship-prompt

# Git-Extras: Adds Git Extras
zplugin ice as"program" pick"$ZPFX/bin/git-*" make"PREFIX=$ZPFX" nocompile
zplugin light tj/git-extras

# Zsh-Completions: Various Command Completions
zplugin ice wait"0" lucid blockf
zplugin light zsh-users/zsh-completions

# You Should Use: Shows unused aliases
zplugin ice wait"0" lucid blockf
zplugin light MichaelAquilina/zsh-you-should-use

# Zsh-Autosuggestions: Because They're Damn Cool
zplugin ice wait"0" lucid atload"_zsh_autosuggest_start"
zplugin light zsh-users/zsh-autosuggestions

# TheFuck: Typo Correction for misspelled commands
zplugin ice wait'1' lucid
zplugin light laggardkernel/zsh-thefuck

# Syntax highlighter: Speed Enhanced
zplugin ice wait"0" lucid atinit"zpcompinit; zpcdreplay"
zplugin light zdharma/fast-syntax-highlighting

# LS_Colors: Trapd00r-Style Shell Coloring
zplugin ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zplugin light trapd00r/LS_COLORS

# Zsh-Autopair: Autoclosing them quotes
zplugin ice wait lucid
zplugin load hlissner/zsh-autopair

# Zlua: Z Replacement
zplugin ice wait"0b" lucid
zplugin light skywind3000/z.lua

# FZF: Fuzzy Finder
zplugin ice from"gh-r" as"program"
zplugin light junegunn/fzf-bin

# Git-Start-Commit: Git smart commits
zplugin ice wait"0b" lucid
zplugin light seletskiy/zsh-git-smart-commands

# FZ: Z Tab-Completions
zplugin ice wait"0" lucid
zplugin light changyuheng/fz

# OMZ's
zplugin snippet OMZ::lib/git.zsh
zplugin snippet OMZ::plugins/asdf/asdf.plugin.zsh
zplugin snippet OMZ::plugins/dotenv/dotenv.plugin.zsh
zplugin snippet OMZ::plugins/fzf/fzf.plugin.zsh
zplugin snippet OMZ::plugins/git/git.plugin.zsh
zplugin snippet OMZ::plugins/heroku/heroku.plugin.zsh
zplugin snippet OMZ::plugins/safe-paste/safe-paste.plugin.zsh
zplugin snippet OMZ::plugins/ssh-agent/ssh-agent.plugin.zsh

# Turbo-enabled CompDefs
autoload -Uz compinit && compinit
#zplugin cdreplay -q
#zplugin cdlist

