#!/usr/bin/bash
# -*- coding: utf-8 -*-
# vim:set ft=zsh ts=2 sw=2 sts=0 foldmethod=marker:

# Emacs
bindkey -e

bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

# Quote pasted URLs#
autoload -Uz history-search-end
autoload -Uz is-at-least
autoload -U url-quote-magic
autoload -U select-word-style
autoload -U edit-command-line
autoload -Uz colors && colors
autoload -U parseopts
autoload -U zargs
autoload -U zcalc
autoload -U zed
autoload -U zmv

zle -N edit-command-line
zle -N expand-or-complete-with-dots
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
zle -N insert-last-command-output
zle -N select-word-style bash
zle -N self-insert url-quote-magic

bindkey " " magic-space
bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word
bindkey "^[[F" end-of-line
bindkey "^[[H" beginning-of-line
#bindkey "^[[Z" autosuggest-accept
bindkey "^E" edit-command-line
bindkey "^I" expand-or-complete-with-dots
bindkey "^N" history-beginning-search-forward-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^X^L" insert-last-command-output

# ------------------------------------------------------------------------------
# Aliases
# ------------------------------------------------------------------------------

# List files
alias ak="tree -C"
alias ak1="tree -L 1 -Ccfhau --du --dirsfirst "
alias ak2="tree -L 2 -Ccfhau --du --dirsfirst "
alias ak3="tree -L 3 -Ccfhau --du --dirsfirst "

# Git
alias ansible-create="ansible-galaxy init  --offline --force"
alias brew_full_upgrade="brew update; brew upgrade; brew cleanup"
alias c="clear"
#alias cat="bat"
alias clip="termux-clipboard-set"
alias code="code-insiders"
alias cp="cp -ri"
alias df="df -hi"
alias diff="meld"
alias du="du -csh"
alias dug="dig +nocmd any +multiline +noall +answer     "
alias fpath='echo $fpath | tr -s " " "\n"'
alias free="free -mt"
alias f="fuck"
alias fzf-preview="fzf --preview bat --style=numbers --color=always {} | head -500"
alias g="git"
alias gc="git commit -am "
alias gch="git checkout "
alias gp="git push --verbose "
alias grep="rg"
alias gs="git status"
alias gsu="git status -uno"
alias h="history"
alias how="howdoi --color --all"
alias httpHeaders="curl -I -L"
alias hu="history | rg -i"
alias l="exa -1 --color=always --group-directories-first --icons --all"
alias lg="lazygit"
alias ls="exa --git --color=always --only-dirs --icons"
alias ll="exa --binary --group --header --all --icons --long --links --inode --classify --blocks --group-directories-first --git-ignore"
alias ls="exa --git --icons --color=always --group-directories-first"
alias lt="exa --git --color=always --only-dirs --icons --tree"
alias mkdir="mkdir -pv"
alias molecule-create="molecule init scenario -r "
alias mtop="htop --sort-key=PERCENT_MEM"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias path='echo $PATH | tr -s ":" "\n"'
alias pip='pip3'
alias python-library="python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'"
alias python='python3'
alias quit="exit"
alias restart='reset; exec sudo --login --user $USER'
alias s3="s3cmd "
alias ssh="TERM=xterm-256color ssh"
alias sublime="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias s="source !$"
alias smerge="/Applications/Sublime\ Merge.app"
alias sudo="sudo "
alias tf="terraform"
alias tf-init-force="rm -rf .terrafor*;tf init"
alias tp="tf plan -out=tfplan"
alias ta="tf apply -auto-approve"
alias ti="tf init"
alias ts="trash "
alias top-ten='print -l -- ${(o)history%% *} | uniq -c | sort -nr | head -n 10'
alias update="brew update && brew upgrade && zinit self-update && zinit update"
alias vim="nvim"
alias v="nvim"
alias vimswap_clean='rm -rf $VIM_SWAP/*'
alias vscode_settings='HOME/Library/Application\ Support/Code/User/settings.json'
alias zb="z -b"
alias zf="z -I"
alias zi="z -i"
alias zi="zinit"
alias zmv="noglob zmv -W"
alias zz="z -c"
alias ga="git add "
