# -*- coding: utf-8 -*-
# vim:set ft=zsh ts=2 sw=2 sts=0 foldmethod=marker:
#!/usr/bin/bash
[[ -f "$HOME/.fig/shell/zprofile.post.zsh" ]] && builtin source "$HOME/.fig/shell/zprofile.post.zsh"
[[ -f "$HOME/.fig/shell/zprofile.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zprofile.pre.zsh"

alias CD="cd"
alias Z="z"
alias ak1="tree -L 1 -Ccfhau --du --dirsfirst "
alias ak2="tree -L 2 -Ccfhau --du --dirsfirst "
alias ak3="tree -L 3 -Ccfhau --du --dirsfirst "
alias ak="tree -C"
alias ansible-create="ansible-galaxy init  --offline --force"
alias b="bat"
alias c="clear"
alias clip="termux-clipboard-set"
alias cp="cp -ri"
alias df="df -hi"
alias diff="vim -d "
alias du="du -csh"
alias dug="dig +nocmd any +multiline +noall +answer     "
alias f="fuck"
alias fat="fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'"
alias fpath='echo $fpath | tr -s " " "\n"'
alias free="free -mt"
alias full_upgrade="brew update; brew upgrade; brew cleanup; zinit update; zinit self-update"
alias fzf="fzf --height=40% --layout=reverse --info=inline --border --margin=1 --padding=1"
alias fzf-preview="fzf --preview bat --style=numbers --color=always {} | head -500"
alias g="git"
alias ga="git add "
alias gc="git commit -am "
alias gch="git checkout "
alias git-co="git-checkout"
alias git-root='cd $(git rev-parse --show-cdup)'
alias gp="git push --verbose "
alias grep="rg"
alias gs="git status"
alias gsu="git status -uno"
alias h="history"
alias how="howdoi --color --all"
alias httpHeaders="curl -I -L"
alias hu="history | rg -i"
alias java_versions="/usr/libexec/java_home -V"
alias l="exa -1 --color=always --group-directories-first --icons --all"
alias lf="exa -1 --color=always --only-dirs --icons --all -D"
alias lg="lazygit"
alias ll="exa --binary --group --header --all --icons --long --links --inode --classify --blocks --group-directories-first --git-ignore"
alias ls="exa --git --color=always --only-dirs --icons"
alias ls="exa --git --icons --color=always --group-directories-first"
alias lsd="ll -D"
alias lt="exa --git --color=always --only-dirs --icons --tree"
alias mkdir="mkdir -pv"
alias molecule-create="molecule init scenario -r "
alias mtop="htop --sort-key=PERCENT_MEM"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias path='echo $PATH | tr -s ":" "\n"'
alias pip="pip3"
alias python-library="python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'"
alias python="python3"
alias quit="exit"
alias restart='reset; exec sudo --login --user "$USER" /bin/sh -c "cd '$PWD'; exec '$SHELL' -l"'
alias rg-dir='rg --hidden --files --null | xargs -0 dirname | uniq | rg '
alias s3="s3cmd "
alias s="source !$"
alias smerge="/Applications/Sublime\ Merge.app"
alias ssh="TERM=xterm-256color ssh"
alias sublime="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias sudo="sudo "
alias t="tre"
alias ta="tf apply -auto-approve"
alias tf-init-force="rm -rf .terrafor*;tf init"
alias tf="terraform"
alias ti="tf init"
alias top-ten="print -l -- ${(o)history%% *} | uniq -c | sort -nr | head -n 10"
alias tp="tf plan -out=tfplan"
alias tree="tre"
alias ts="trash "
alias ts="trash "
alias update="brew update && brew upgrade && zinit self-update && zinit update"
alias v="fzf --print0 | xargs -0 -o nvim"
alias vim="nvim"
alias vimswap_clean='rm -rf $VIM_SWAP/*'
alias vscode_settings='HOME/Library/Application\ Support/Code/User/settings.json'
alias wipe="echo '' > "
#alias zb="z -b"
#alias zf="z -I"
#alias zi="z -i"
alias zmv="noglob zmv -W"
#alias zz="z -c"

autoload -U edit-command-line
autoload -U parseopts
autoload -U select-word-style
autoload -U url-quote-magic
autoload -U zargs
autoload -U zcalc
autoload -U zed
autoload -U zmv
autoload -Uz colors && colors
autoload -Uz history-search-end
autoload -Uz is-at-least

bindkey " " magic-space
bindkey "^E" edit-command-line
bindkey "^I" expand-or-complete-with-dots
bindkey "^N" history-beginning-search-forward-end
bindkey "^N" history-beginning-search-forward-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^X^L" insert-last-command-output
bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word
bindkey "^[[F" end-of-line
bindkey "^[[H" beginning-of-line
bindkey -e

zle -N edit-command-line
zle -N expand-or-complete-with-dots
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
zle -N insert-last-command-output
zle -N select-word-style bash
zle -N self-insert url-quote-magic
