#! /usr/bin/env zsh
# -*- coding: utf-8 -*-
# vim: set sts=2 sw=2 ts=

# Set Options
setopt AUTO_CD                # Navigate without typing cd
setopt BANG_HIST              # Treat '!' char specially during expansion.
setopt CHASE_LINKS            # Resolve links to their location
setopt EXTENDED_HISTORY       # Use history ":start:elapsed;command" format.
setopt HASH_CMDS              # Dont search for commands
setopt HASH_LIST_ALL          # More accurate correction
setopt HIST_EXPIRE_DUPS_FIRST # Remove dupes first when trimming history.
setopt HIST_IGNORE_SPACE      # Don't record starting with a space.
setopt HIST_REDUCE_BLANKS     # Remove superfluous blanks before recording.
setopt HIST_SAVE_NO_DUPS      # Don't write dupes in the history file.
setopt HIST_VERIFY            # Don't execute immediately upon expansion.
setopt INC_APPEND_HISTORY     # Write to the history file immediately.
setopt INTERACTIVE_COMMENTS   # Allow comments in readlin
setopt LIST_ROWS_FIRST        # Rows are way better
setopt LIST_TYPES             # Append type chars to files
setopt MULTIOS                # Write to multiple descriptors
setopt PROMPTSUBST            # Enable param and arithmetic substitution
setopt RC_QUOTES              # Allow 'Henry''s Garage'
setopt SHARE_HISTORY          # Share history between all sessions.
setopt shwordsplit            # Word splits like Bash
setopt SHORT_LOOPS            # Sooo lazy: for x in y do cmd
setopt SUN_KEYBOARD_HACK      # Ignore rogue backquote
unsetopt FLOW_CONTROL         # Disable /stop characters editor

# Folders
export DOTFILES="$HOME/.dotfiles"
export CACHE="$HOME/.cache"
export CONFIG="$HOME/.config"

# Automatically remove duplicates from these arrays
typeset -U path PATH cdpath CDPATH fpath FPATH manpath MANPATH

# Load Custom Functions
fpath=( $DOTFILES/functions "${fpath[@]}" )
autoload -Uz $fpath[1]/*(.:t)

# System Paths
path=(
  $HOME/.local/bin
  $HOME/Library/Python/{3.7,3.8}/bin
  /usr/local/{bin,sbin}
  /opt/homebrew/bin
  /usr/{bin,sbin}
  $path
)

# Zsh-Autosuggest
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=240"
export ZSH_AUTOSUGGEST_USE_ASYNC="1"
export ZSH_AUTOSUGGEST_MANUAL_REBIND="1"
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="1"
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# Terminal
export REPORTTIME="2"
export TIMEFMT="%U user %S system %P cpu %*Es total"
export KEYTIMEOUT="1"
export ITERM_24BIT="1"
export WORDCHARS='*?-[]~\!#%^(){}<>|`@#%^*()+:?'
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY="YES"

# Editor
export EDITOR="$(which nvim)"
export VISUAL="$EDITOR"

# Python
export PYTHONDONTWRITEBYTECODE=true
export PYTHONSTARTUP="$HOME/.python_startup.py"

# Pager
#export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANPAGER="nvim -c 'set ft=man' -"
export BAT_CONFIG_PATH="$DOTFILES/configs/bat.conf"

# Ruby
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

# FZF
export FZF_BASE=$(which fzf)
export FZF_COMPLETION_TRIGGER='~~'
export FZF_DEFAULT_COMMAND='rg --files --hidden'
export FZF_CTRL_T_COMMAND='rg --files --hidden'
export FZF_DEFAULT_OPTS='--cycle --reverse --no-height  --exit-0 --bind=ctrl-j:accept --color=dark --color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f --color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Zlua
[[ ! -f "$CACHE/z.lua" ]] || touch "$CACHE/z.lua"
export _ZL_DATA="$CACHE/z.lua"
export _ZL_MATCH_MODE="1"
export _ZL_HYPHEN="1"
export _ZL_ECHO="1"

# FZ
FZ_HISTORY_CD_CMD="_zlua"

# History
export HISTFILE=$CACHE/.zsh_history
export ZSH_PECO_HISTORY_OPTS="--layout=bottom-up --initial-filter=Fuzzy"
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"
export HISTSIZE=10000
export SAVEHIST=10000

# bash completions
autoload bashcompinit && bashcompinit

# Menu-like autocompletion selection
zmodload -i zsh/complist

# Enable completion and other things.
autoload -Uz run-help zargs zrecompile
autoload -Uz compinit && compinit -d $ZDOTDIR/zcompdump

# Autocomplete hidden files
zstyle ':completion:*' file-patterns '%p(D):globbed-files *(D-/):directories' '*(D):all-files'

# case insensitive path-completion
zstyle ':completion:*' matcher-list                       \
'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'             \
'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' \
'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' \
'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

# partial completion suggestions
zstyle ':completion:*'                list-suffixes
zstyle ':completion:*'                expand prefix suffix

# speedup path completion
zstyle ':completion:*'                accept-exact '*(N)'
zstyle ':completion:*'                use-cache on
zstyle ':completion:*'                cache-path ${CACHE}/zsh
zstyle ':completion:*'                use-perl on

# colors
zstyle ':completion:*:default'        list-colors '${(s.:.)LS_COLORS}'

# manuals
zstyle ':completion:*:manuals'        separate-sections true
zstyle ':completion:*:manuals.(^1*)'  insert-sections   true
zstyle ':completion:*:man:*'          menu yes select

# Fuzzy match mistyped completions.
zstyle ':completion:*'                completer _complete _list _match _approximate
zstyle ':completion:*:match:*'        original only
zstyle ':completion:*:approximate:*'  max-errors 1 numeric

# Don't complete unavailable commands.
zstyle ':completion:*:functions'      ignored-patterns '(_*|pre(cmd|exec))'

# Array completion element sorting.
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters

# Automatically find new executables in path
zstyle ':completion:*'                 rehash true

# Man
zstyle ':completion:*:manuals'         separate-sections true
zstyle ':completion:*:manuals.(^1*)'   insert-sections true

# Completion Style
zstyle ':completion:*:*:cd:*'          ignore-parents parent pwd
zstyle ':completion:*:*:cd:*'          tag-order local-directories directory-stack path-directories
zstyle ':completion:*:*:cd:*'          menu yes select

# Avoid twice the same element on rm
zstyle ':completion:*:rm:*'            ignore-line yes

# Insert all expansions for expand completer
zstyle ':completion:*:expand:*'        tag-order all-expansions

# History
zstyle ':completion:*:history-words'   list false
zstyle ':completion:*:history-words'   menu yes
zstyle ':completion:*:history-words'   remove-all-dups yes
zstyle ':completion:*:history-words'   stop yes
