#! /usr/bin/env zsh
# -*- coding: utf-8 -*-
# vim: set sts=2 sw=2 ts=

# Set Options
setopt AUTO_CD                # Navigate without typing cd
setopt BANG_HIST              # Treat '!' char specially during expansion.
setopt CHASE_LINKS            # Resolve links to their location
setopt EXTENDED_HISTORY       # Use history ":start:elapsed;command" format.
setopt HASH_CMDS              # Dont search for commands
setopt HASH_LIST_ALL          # More accurate correction
setopt HIST_EXPIRE_DUPS_FIRST # Remove dupes first when trimming history.
setopt HIST_IGNORE_SPACE      # Don't record starting with a space.
setopt HIST_REDUCE_BLANKS     # Remove superfluous blanks before recording.
setopt HIST_SAVE_NO_DUPS      # Don't write dupes in the history file.
setopt HIST_VERIFY            # Don't execute immediately upon expansion.
setopt INC_APPEND_HISTORY     # Write to the history file immediately.
setopt INTERACTIVE_COMMENTS   # Allow comments in readlin
setopt LIST_ROWS_FIRST        # Rows are way better
setopt LIST_TYPES             # Append type chars to files
setopt MULTIOS                # Write to multiple descriptors
setopt PROMPT_SUBST           # Enable param and arithmetic substitution
setopt RC_QUOTES              # Allow 'Henry''s Garage'
setopt SHARE_HISTORY          # Share history between all sessions.
setopt shwordsplit            # Word splits like Bash
setopt SHORT_LOOPS            # Sooo lazy: for x in y do cmd
setopt SUN_KEYBOARD_HACK      # Ignore rogue backquote
unsetopt FLOW_CONTROL         # Disable /stop characters editor

# Folders
export DOTFILES="$HOME/.dotfiles"
export CACHE="$HOME/.cache"
export CONFIG="$HOME/.config"

# Zsh-Autosuggest
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=240"
export ZSH_AUTOSUGGEST_USE_ASYNC="1"
export ZSH_AUTOSUGGEST_MANUAL_REBIND="1"
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="1"
export ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(vi-end-of-line)
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# Terminal
export REPORTTIME="2"
export TIMEFMT="%U user %S system %P cpu %*Es total"
export KEYTIMEOUT="1"
export ITERM_24BIT="1"
export WORDCHARS='*?-[]~\!#%^(){}<>|`@#%^*()+:?'
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY="YES"

# Editor
export EDITOR="$(which nvim)"
export VISUAL="$EDITOR"

# Python
export PYTHONDONTWRITEBYTECODE=true
export PYTHONSTARTUP="$HOME/.python_startup.py"

# Pager
export PAGER="$(which bat)"
#export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANPAGER="nvim -c 'set ft=man' -"
export BAT_CONFIG_PATH="$DOTFILES/bat.conf"

# Ruby
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

# FZF
export FZF_BASE=$(which fzf)
export FZF_COMPLETION_TRIGGER='~~'
export FZF_DEFAULT_COMMAND='rg --files --hidden'
export FZF_CTRL_T_COMMAND='rg --files --hidden'
export FZF_DEFAULT_OPTS='--cycle --no-reverse --no-height  --exit-0 --bind=ctrl-j:accept --color=dark --color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f --color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7'

# FZF Helper Function
#_fzf_setup_completion path ag git kubectl
#_fzf_setup_completion dir tree

# Zlua
[[ ! -f "$CACHE/z.lua" ]] || touch "$CACHE/z.lua"
export _ZL_DATA="$CACHE/z.lua"
export _ZL_MATCH_MODE="1"
export _ZL_HYPHEN="1"
export _ZL_ECHO="1"

# FZ
FZ_HISTORY_CD_CMD="_zlua"

# History
export HISTFILE=$CACHE/.zsh_history
export ZSH_PECO_HISTORY_OPTS="--layout=bottom-up --initial-filter=Fuzzy"
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"
export HISTSIZE=10000
export SAVEHIST=10000

# Automatically remove duplicates from these arrays
typeset -U path PATH cdpath CDPATH fpath FPATH manpath MANPATH

fpath=( $DOTFILES/functions "${fpath[@]}" )
autoload -Uz $fpath[1]/*(.:t)

# System Paths
path=(
  $(brew --prefix)/{sbin,bin}
  $HOME/.local/bin
  $HOME/Library/Python/{3.7,3.8}/bin
  /usr/local/opt/coreutils/libexec/gnubin
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)


#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# vim:set ft=zsh ts=2 sw=2 sts=0 foldmethod=marker:

autoload -U edit-command-line && zle -N edit-command-line
autoload -Uz url-quote-magic && zle -N self-insert url-quote-magic
autoload -Uz bracketed-paste-magic && zle -N bracketed-paste bracketed-paste-magic
autoload -U select-word-style && zle -N select-word-style bash

autoload -U +X bashcompinit && bashcompinit
autoload -Uz colors && colors

zle -N expand-or-complete-with-dots &&\
  zle -N history-beginning-search-backward-end history-search-end &&\
  zle -N history-beginning-search-forward-end history-search-end



autoload -Uz history-search-end
autoload -Uz is-at-least
zle -N autosuggest-accept

autoload -U \
    parseopts \
    zargs \
    zcalc \
    zed \
    zmv


zle -N insert-last-command-output



# Emacs
bindkey -e

bindkey "^I" expand-or-complete-with-dots
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end
bindkey " " magic-space
bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word
bindkey "^[[F" end-of-line
bindkey "^[[H" beginning-of-line
bindkey "^N" history-beginning-search-forward-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^X^L" insert-last-command-output
bindkey "^E" edit-command-line
bindkey '^ ' autosuggest-accept
