#!/usr/local/bin/zsh
# vim:set ft=zsh ts=4 sw=4 sts=0
# -----------------------------------------------------------------------------
# file: zshrc
# info: main configuration file
# name: andrew kuttor
# mail: andrew.kuttor@gmail.com
# -----------------------------------------------------------------------------
limit coredumpsize 0
skip_global_compinit=1
local SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#if [[ ! -d $ZPLUG/.zplug ]]; then
#  echo "Installing zplug"
#  curl -sL https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
#fi

# Quote pasted URLs
autoload -U url-quote-magic
zle -N self-insert url-quote-magic

# Use ZMV, which is amazing
autoload -U zmv
alias zmv="noglob zmv -W"

# run-help
autoload -Uz run-help-git
autoload -Uz run-help-svk
autoload -Uz run-help-svn

# ENHANCD
ENHANCD_COMMAND="cdd"
ENHANCD_DIR="$HOME/.config/enhancd/"
ENHANCD_FILTER="z"
ENHANCD_DOT_SHOW_FULLPATH=1

# Manage SSH keys with keychain
if $(command -v keychain > /dev/null)
then
  keychain id_rsa
  source "$HOME/.keychain/$(hostname)-sh"
fi

# Sources
# ==============================================================================
source "$SCRIPTPATH/env.zsh"
source "$SCRIPTPATH/paths.zsh"
source "$SCRIPTPATH/aliases.zsh"
source "$SCRIPTPATH/colors.zsh"
source "$SCRIPTPATH/completes.zsh"
source "$SCRIPTPATH/history.zsh"
source "$SCRIPTPATH/keybinds.zsh"
source "$SCRIPTPATH/options.zsh"
source "$SCRIPTPATH/zplug.zsh"
source "$HOME/.iterm2_shell_integration.zsh"

