# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#! /bin/env zsh
# -*- coding: utf-8 -*-
# vim: set sts=2 sw=2 ts=2

skip_global_compinit="1"
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Oh-My-zShell
zinit light-mode for                                 \
    OMZ::lib/clipboard.zsh                           \
    OMZ::lib/compfix.zsh                             \
    OMZ::lib/completion.zsh                          \
    OMZ::lib/correction.zsh                          \
    OMZ::lib/directories.zsh                         \
    OMZ::lib/functions.zsh                           \
    OMZ::lib/git.zsh                                 \
    OMZ::lib/history.zsh                             \
    OMZ::lib/key-bindings.zsh                        \
    OMZ::lib/spectrum.zsh                            \
    OMZ::lib/termsupport.zsh                         \
    Aloxaf/fzf-tab                                   \
    joshskidmore/zsh-fzf-history-search              \
    andrewferrier/fzf-z                              \
    changyuheng/fz                                   \
    chitoku-k/fzf-zsh-completions                    \
    djui/alias-tips                                  \
    eastokes/aws-plugin-zsh                          \
    hlissner/zsh-autopair                            \
    kutsan/zsh-system-clipboard                      \
    unixorn/docker-helpers.zshplugin                 \
    greymd/docker-zsh-completion                     \
    macunha1/zsh-terraform                           \
    nojanath/ansible-zsh-completion                  \
    paw-lu/pip-fzf                                   \
    rapgenic/zsh-git-complete-urls                   \
    rupa/v                                           \
    FFKL/s3cmd-zsh-plugin                            \
    skywind3000/z.lua                                \
    sparsick/ansible-zsh                             \
    srijanshetty/zsh-pip-completion                  \
    atinit"zicompinit; zicdreplay"                   \
        zdharma-continuum/fast-syntax-highlighting   \
    atload"_zsh_autosuggest_start"                   \
        zsh-users/zsh-autosuggestions                \
    blockf atpull'zinit creinstall -q .'             \
        zsh-users/zsh-completions

# Turbo-enabled CompDefs
autoload -Uz compinit && compinit
zinit cdreplay -q

# Load Prompt
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Source ZProfile
source $HOME/.zprofile
