#!/bin/bash

# Aliases for both Bash and Zsh.

# By: Andrew Kuttor
# Contact: andrew.kuttor@gmail.com

#------------------------------------------------------------------------------
# Package Management
#------------------------------------------------------------------------------

alias pip-upgrade="pip freeze --local | grep -v '^\-e' |\
	cut -d = -f 1  | xargs pip install --user"
alias apt-upgrade='sudo apt-get update && sudo apt-get upgrade &&\
	sudo apt-get autoremove'

#------------------------------------------------------------------------------
# Terminal
#------------------------------------------------------------------------------

alias fix_stty='stty sane'
alias path='echo $PATH | tr -s ":" "\n"'
alias quit='exit'
alias rm='rm -ii'
alias which='type -all'

#------------------------------------------------------------------------------
# Server Managemet
#------------------------------------------------------------------------------

alias ssh_host_list='grep "^Host" $HOME/.ssh/config | awk "{print $2}"'

#------------------------------------------------------------------------------
# Networking
#------------------------------------------------------------------------------

alias myip='curl ip.appspot.com'                # Public facing IP Address
alias netCons='lsof -i'                         # Show all open TCP/IP sockets
alias allopensockets='sudo lsof -i -P'          # Show open sockets
alias openudpsockets='sudo lsof -nP | grep UDP' # Show only open UDP sockets
alias opentcpsockets='sudo lsof -nP | grep TCP' # Show only open TCP sockets
alias showlistening='sudo lsof -i | grep LISTEN'    # All listening connections
alias ports='netstat -lantip'

#------------------------------------------------------------------------------
# Editors
#------------------------------------------------------------------------------

alias vim='nvim' # Neovim
alias vi='nvim'  # Neovim
alias less='less +g -RSC~'

#------------------------------------------------------------------------------
# File and folder management
#------------------------------------------------------------------------------

alias mkdir="mkdir -pv"
alias df='df -hi'
alias du='du -h'
alias free='free -mt'
alias rm='rm -ii'
alias cp="cp -ri"       # Sets recursive and requires confirm overwrite
