#! /bin/bash

# Author: Andrew Kuttor
# E-mail: andrew.kuttor@gmail.com

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT_DIR="$(dirname $(readlink -f $BASH_SOURCE))/" 

#-------------------------------------------------------------------------------
# Terminal
#-------------------------------------------------------------------------------

safe_term=${TERM//[^[:alnum:]]/?}   # sanitize TERM

# If not interactive do not pass go
case $- in
	*i*) ;;
	*) return;;
esac

# Promotes faster Terminal starts
sudo rm -rf /private/var/log/asl/*.asl

# Assigns perms so that current user only has read and write access
umask 022

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

#-------------------------------------------------------------------------------
# BUILTINS
#-------------------------------------------------------------------------------

shopt -s autocd         # Auto cd when navigating file system
shopt -s nocaseglob     # Case in-sensitive globbing
shopt -s cdspell        # Autocorrect typos in path when using cd
shopt -s checkwinsize   # Checks/Modifies term window size per command
shopt -s progcomp       # Programmable completions
shopt -s expand_aliases # Expands aliases while in use

#-------------------------------------------------------------------------------
# Evals
#-------------------------------------------------------------------------------

# Hub: https://github.com/github/hub
eval "$(hub alias -s)"

#-------------------------------------------------------------------------------
# Pretty Lights
#-------------------------------------------------------------------------------

# Detect GNU or OSX ls 
if [[ "ls --color /dev/null 2>&1" ]]
then
    colorflag="--color=auto" # GNU
else
    colorflag="-G"           # OSX
fi

eval $(dircolors -b $SCRIPT_DIR/dircolors) # Coloring for 300 filetypes

# alias ls="ls -AFoqv --color --group-directories-first | tail -n +3"
alias ls="ls -AFoqv $colorflag --group-directories-first"
alias grep="grep $colorflag"
alias egrep="egrep $colorflag"
alias fgrep="fgrep $colorflag"

#-------------------------------------------------------------------------------
# Completions
#-------------------------------------------------------------------------------

# Enable programmable completions
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Tab completions with sudo
complete -cf sudo

# FZF
. /usr/share/fzf/completion.bash

#-------------------------------------------------------------------------------
# Keybindings
#-------------------------------------------------------------------------------

# FZF
. /usr/share/fzf/key-bindings.bash

#------------------------------------------------------------------------------
# Sources
#-------------------------------------------------------------------------------

# Aliases
[[ -f "$SCRIPT_DIR/aliases" ]] && . "$SCRIPT_DIR/aliases"

# Functions
[[ -f "$SCRIPT_DIR/functions" ]] && . "$SCRIPT_DIR/functions"

# History
[[ -f "$SCRIPT_DIR/history" ]] && . "$SCRIPT_DIR/history"

# Exports
[[ -f "$SCRIPT_DIR/exports" ]] && . "$SCRIPT_DIR/exports"
