#!/bin/bash

# Author: Andrew Kuttor
# E-mail: andrew.kuttor@gmail.com

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT_DIR="$(dirname $(readlink -f $BASH_SOURCE))/" 

#-------------------------------------------------------------------------------
# Terminal
#-------------------------------------------------------------------------------

safe_term=${TERM//[^[:alnum:]]/?}   # sanitize TERM

# If not interactive do not pass go
case $- in
	*i*) ;;
	*) return;;
esac


#-------------------------------------------------------------------------------
# BUILTINS
#-------------------------------------------------------------------------------

shopt -s autocd         # Auto cd when navigating file system
shopt -s nocaseglob     # Case in-sensitive globbing
shopt -s histappend     # Append to history
shopt -s cdspell        # Autocorrect typos in path when using cd
shopt -s checkwinsize   # Checks/Modifies term window size per command
shopt -s progcomp       # Programmable completions
shopt -s expand_aliases # Expands aliases while in use

#-------------------------------------------------------------------------------
# Exports and Special Aliases
#-------------------------------------------------------------------------------

# FZF --top-down --bordeer --start-below-curser
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

# Hub: https://github.com/github/hub
eval "$(hub alias -s)"

#-------------------------------------------------------------------------------
# Pretty Lights
#-------------------------------------------------------------------------------

# Detect GNU or OSX ls 
if [[ "ls --color /dev/null 2>&1" ]]
then
    colorflag="--color=auto" # GNU
else
    colorflag="-G"           # OSX
fi

eval $(dircolors -b $SCRIPT_DIR/dircolors) # Coloring for 300 filetypes

# alias ls="ls -AFoqv --color --group-directories-first | tail -n +3"
alias ls="ls -AFoqv $colorflag --group-directories-first"
alias grep="grep $colorflag"
alias egrep="egrep $colorflag"
alias fgrep="fgrep $colorflag"

# better yaourt colors
export YAOURT_COLORS="nb=1:pkg=1:ver=1;32:lver=1;45:installed=1;42:grp=1;\
	34:od=1;41;5:votes=1;44:dsc=0:other=1;35"


#-------------------------------------------------------------------------------
# History
#-------------------------------------------------------------------------------
alias h=history
export HISTSIZE='32768'           # Assign enlarged history file size to var
export HISTFILESIZE="${HISTSIZE}" # Sets new history limit
export HISTCONTROL='ignoreboth'   # No dupes, No leading spaces
export PROMPT_COMMAND="h -a; h -c; h -r; $PROMPT_COMMAND" # Reload after cmds


#-------------------------------------------------------------------------------
# Langs
#-------------------------------------------------------------------------------

# Set English and UTF-8
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'


#-------------------------------------------------------------------------------
# Completions
#-------------------------------------------------------------------------------

# Enable programmable completions
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Tab completions with sudo
complete -cf sudo

# FZF
. /usr/share/fzf/completion.bash

#-------------------------------------------------------------------------------
# Extras
#-------------------------------------------------------------------------------

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# KDE Konsol app blurry backgrounds
#konsolex=$(qdbus | grep konsole | cut -f 2 -d\ )
#if [ -n "$konsolex" ]; then
#  for konsole in `xdotool search --class konsole`; do
#    xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c \
#          -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 \
#          -id $konsole
#  done
#fi

# Promotes faster Terminal starts
sudo rm -rf /private/var/log/asl/*.asl

# Assigns perms so that current user only has read and write access
umask 022


#-------------------------------------------------------------------------------
# Keybindings
#-------------------------------------------------------------------------------

# FZF
. /usr/share/fzf/key-bindings.bash

#------------------------------------------------------------------------------
# Sources
#-------------------------------------------------------------------------------

# Aliases
[[ -f "$SCRIPT_DIR/aliases" ]] && . "$SCRIPT_DIR/aliases"

# Functions
[[ -f "$SCRIPT_DIR/functions" ]] && . "$SCRIPT_DIR/functions"

