#! /bin/bash

# Author: Andrew Kuttor
# E-mail: andrew.kuttor@gmail.com

# =============================================================================
# Colors
# =============================================================================

# Detect GNU or OSX ls 
if [[ "ls --color /dev/null 2>&1" ]]
then
    colorflag="--color=auto" # GNU
else
    colorflag="-G"           # OSX
fi

eval $(dircolors -b $SCRIPT_DIR/dircolors) # Coloring for 300 filetypes

# alias ls="ls -AFoqv --color --group-directories-first | tail -n +3"
alias ls="ls -AFoqv $colorflag --group-directories-first"
alias grep="grep $colorflag"
alias egrep="egrep $colorflag"
alias fgrep="fgrep $colorflag"

# Use GRC for more colorization
GRC=$(which grc)
if [ -n GRC ]; then
    alias colourify='$GRC -es --colour=auto'
    alias as='colourify as'
    alias configure='colourify ./configure'
    alias diff='colourify diff'
    alias dig='colourify dig'
    alias g++='colourify g++'
    alias gas='colourify gas'
    alias gcc='colourify gcc'
    alias head='colourify head'
    alias ifconfig='colourify ifconfig'
    alias ld='colourify ld'
    alias ls='colourify ls'
    alias make='colourify make'
    alias mount='colourify mount'
    #mtr
    alias netstat='colourify netstat'
    alias ping='colourify ping'
    alias ps='colourify ps'
    alias tail='colourify tail'
    alias traceroute='colourify traceroute'
fi
