#! /bin/bash

# Author: Andrew Kuttori
# E-mail: andrew.kuttor@gmail.com

# =============================================================================
# Exports
# =============================================================================

# Force virtualenv got Pip package installs
export PIP_REQUIRE_VIRTUALENV=true

# Set FZF defaults and size
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

# Language 
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# better yaourt colors
export YAOURT_COLORS="nb=1:pkg=1:ver=1;32:lver=1;45:installed=1;42:grp=1;\
	34:od=1;41;5:votes=1;44:dsc=0:other=1;35"


