#! /bin/bash

# Author: Andrew Kuttor
# E-mail: andrew.kuttor@gmail.com

# =============================================================================
# History
# =============================================================================


# Append to the history file, don't overwrite it.
shopt -s histappend

# Allow us to re-edit a failed history substitution.
shopt -s histreedit

# History expansions will be verified before execution.
shopt -s histverify

# Alias history command to "h"
alias h=history

# Set history file size
export HISTSIZE="32768"

# Set history limit
export HISTFILESIZE="${HISTSIZE}"

# Ignore recording leading spaces and dupes
export HISTCONTROL='ignoreboth'

# export PROMPT_COMMAND="h -a; h -c; h -r; $PROMPT_COMMAND" # Reload after cmds

# Specify commands to ignore recording to history file
export HISTIGNORE="ls:ll:cd:cd -:pwd:exit:date:histoiry"

# History format
export HISTTIMEFORMAT="[%F %T] "
