#! /bin/bash

# =============================================================================
# Install
# =============================================================================

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

# =============================================================================
# Setup 
# =============================================================================

# Configuration+.
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

# Keybindings
. /usr/share/fzf/key-bindings.bash

# Completion
. /usr/share/fzf/completion.bash

# =============================================================================
# Functions 
# =============================================================================

# fh - repeat history
fh() {
  eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}

 
